name: Build TeslaDecrypt

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install OpenSSL
      run: |
        choco install openssl
        echo "OPENSSLDIR=C:\Program Files\OpenSSL-Win64" >> $GITHUB_ENV

    - name: Build with Visual Studio
      run: |
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -S . -B build
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" --build build --config Release

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: TeslaDecrypt-Binary
        path: build/Release/*.exe
