name: Build TeslaDecrypt on macOS

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        # Install dependencies using Homebrew or other methods
        brew install openssl
        # Add other dependencies as needed

    - name: Build with MSBuild for Mac
      run: |
        msbuild TeslaDecrypter.vcxproj /p:Configuration=Release
