name: Build TeslaDecrypt

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Manually Install Dependencies
      run: |
        # TODO: Add steps to manually download and install OpenSSL and vcredist2015
  
    - name: Build with Visual Studio
      run: |
        cmd /c "`"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe`" -S . -B build"
        cmd /c "`"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe`" --build build --config Release"


  

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: TeslaDecrypt-Binary
        path: build/Release/*.exe
