name: Build TeslaDecrypt

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Manually Install Dependencies
      run: |
        # TODO: Add steps to manually download and install OpenSSL and vcredist2015
  
    - name: Build with MSBuild
      run: |
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" TeslaDecrypter.sln /p:Configuration=Release



  

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: TeslaDecrypt-Binary
        path: build/Release/*.exe
